## 更改服务应用名
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.106:3306/springcloud_sell?serverTimezone=Asia/Shanghai&userUnicode=True&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
## 将该服务注册到注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

## 设置负载均衡配置
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
