## \u670D\u52A1\u6CE8\u518C
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

## \u4FEE\u6539\u5E94\u7528\u540D
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.106:3306/springcloud_sell?serverTimezone=Asia/Shanghai&userUnicode=True&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true