## \u66F4\u6539\u670D\u52A1\u5E94\u7528\u540D
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.106:3306/springcloud_sell?serverTimezone=Asia/Shanghai&userUnicode=True&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
## \u5C06\u8BE5\u670D\u52A1\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

## \u8BBE\u7F6E\u8D1F\u8F7D\u5747\u8861\u914D\u7F6E
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
